DolceMusic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('search/', include('music_search.urls')),
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path('log/', include('accounts.urls')),
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
    path('', views.home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from . import views
app_name = 'accounts'
urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
]

music_search/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'music_search'
urlpatterns = [
    path('', views.index, name='index'),
    # periods path
    path('periods/', views.PeriodView.as_view(), name='period'),
    path('periods/downl', views.get_per_file, name='excel_period'),
    path('periods/excel_upd', views.post_per_file, name='post_excel_period'),
    path('periods/<int:pk>/details',
         views.DetailView.as_view(), name='detail_period'),
    path('periods/<int:pk>/edit',
         views.PeriodUpdate.as_view(), name='edit_period'),
    path('periods/create', views.PeriodCreate.as_view(), name='create_period'),
<<<<<<< HEAD
    path('periods/<int:pk>/delete',
         views.PeriodDelete.as_view(), name='delete_period'),
    # compousers path
    path('compousers/downl', views.get_comp_file, name='excel_compouser'),
    path('compousers/excel_upd', views.post_comp_file, name='post_excel_compouser'),
=======
    # compousers path
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
    path('compousers/', views.CompousersView.as_view(), name='compouser'),
    path('compousers/<int:pk>/details',
         views.CompousersDetailView.as_view(), name='detail_compouser'),
    path('compousers/<int:pk>/edit',
         views.CompousersUpdate.as_view(), name='edit_compouser'),
    path('compousers/create_compouser', views.CompousersCreate.as_view(),
<<<<<<< HEAD
         name='create_compouser'),
    path('compousers/<int:pk>/delete',
         views.CompousersDelete.as_view(), name='delete_compouser'),
     # music path
     path('music/downl', views.get_music_file, name='excel_music' ),
     path('music/excel_upd', views.post_music_file, name='post_excel_music'),
     path('music/', views.PieceOfMusicView.as_view(), name='music'),
     path('music/<int:pk>/details', views.MusicDetailView.as_view(), name='detail_music'),
     path('music/<int:pk>/edit', views.PieceOfMusicUpdate.as_view(), name='edit_music'),
     path('music/create_music', views.PieceOfMusicCreate.as_view(), name='create_music'),
     path('music/<int:pk>/delete', views.PieceOfMusicDelete.as_view(), name='delete_music')
=======
         name='create_compouser')
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_search/forms.py
from django import forms
from django.core.validators import RegexValidator
<<<<<<< HEAD
from django.contrib.auth.forms import ReadOnlyPasswordHashField
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
from django.forms import ModelForm
from .validators import *
from .models import *

<<<<<<< HEAD
=======

>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
class PeriodForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', }), validators=[RegexValidator(regex='^\w+$')])
    time_of_period = forms.CharField(validators=[RegexValidator(
        regex='^[1-9]([0-9]{3})[-][1-9]([0-9]{3})$', message='invalid time period', code='invalid_period'), validate_year], widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Period
        fields = '__all__'

    def clean(self):
        cleaned_data = super(PeriodForm, self).clean()
        time_of_period = cleaned_data.get("time_of_Period")
        name = cleaned_data.get("name")
        descr = cleaned_data.get("descr")
        if name is not None and time_of_period is not None and descr is not None:
            if not validate_year(time_of_period):
                raise ValidationError('incorect period year validation')
            elif name == None:
                raise ValidationError('name cannot be empty')


class CompousersForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', }), validators=[RegexValidator(regex='\w+')])
    birth_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control'}))
    death_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control'}))

    class Meta:
<<<<<<< HEAD
        model = Compouser
=======
        model = Compousers
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
        fields = '__all__'

    def clean(self):
        cleaned_data = super(CompousersForm, self).clean()
        name = cleaned_data.get("name")
        birth_date = cleaned_data.get("birth_date")
        death_date = cleaned_data.get("death_date")

<<<<<<< HEAD
class MusicForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', }), validators=[RegexValidator(regex='\w+')])
    year_written = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control'}))
    class Meta:
        model = PieceOfMusic
        fields = '__all__'

    def clean(self):
        cleaned_data = super(MusicForm, self).clean()
        name = cleaned_data.get("name")
        year_written = cleaned_data.get("year_written")

=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e

'''class PeriodEditFrom(forms.Form):
    period_name = forms.CharField(lable='Period name', max_length = 100)
    period_time = forms.CharField(lable='Period time', max_length = 9)'''

music_search/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.template.response import TemplateResponse
from django.http import HttpResponse, request, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
<<<<<<< HEAD
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.template.defaulttags import register

import openpyxl
import io
import xlsxwriter
from django.utils.translation import ugettext
from .fusioncharts import FusionCharts
import re

from .forms import *
from .models import *
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .decorators import admin_required
=======
from .forms import *
from .models import *
from .fusioncharts import FusionCharts
#from .forms import PeriodEditFrom
# Create your views here.
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e


@login_required
def index(request):
    return TemplateResponse(request, 'search.html', {})


def home_view(request):
    period_values = Period.objects.order_by('time_of_period').values('name')
    context = {'period_names': period_values}

    return render(request, 'music_search/index.html', context)

def validate_period(value):
    characters = value.split('-')
    check = True

    if len(characters) != 2:
        return False

    first_date = characters[0]
    second_date = characters[1]

    if not first_date.isdigit() or not second_date.isdigit():
        return False
    else:
        first_date = int(first_date)
        second_date = int(second_date)

    if first_date >= second_date:
        check = False

    if second_date - first_date > 500:
        check = False

    return check

def validate_date(value):
    check = False
    if re.match(r"([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))", value):
        check = True
    return check

class PeriodView(LoginRequiredMixin, generic.ListView):
    model = Period
    template_name = 'music_search/periods.html'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super(PeriodView, self).get_context_data(**kwargs)

        period_values = Period.objects.order_by(
            'time_of_period').values('time_of_period', 'name', 'id')
        context['period_list'] = Period.objects.order_by('time_of_period')
        context['header'] = list(period_values[0].keys())[:-1]
        context['content_period'] = list(period_values)
        return context

@admin_required
def post_per_file(request):
    periods = Period.objects.all()
    period_values = Period.objects.order_by(
        'time_of_period').values('time_of_period', 'name', 'descr', 'id')
    
    template_name = 'music_search/periods.html'

    if request.method == 'POST' and request.FILES['excel-file']:
        excel_file = request.FILES['excel-file']
        fs = FileSystemStorage()
        filename = fs.save(excel_file.name, excel_file)
        uploaded_file_url = fs.url(filename)

<<<<<<< HEAD
        wb = openpyxl.load_workbook(excel_file)

        worksheet = wb[wb.sheetnames[0]]

        period_name = [period['name'] for period in period_values]
        period_year = [period['time_of_period'] for period in period_values]
        period_descr = [period['descr'] for period in period_values]

        
        i = 0
        for data in worksheet.iter_rows(min_row=1, max_col=4, values_only=True):
    
            if i == 0:
                i += 1
                continue
            i += 1

            name = data[1]

            if name == None:
                break

            elif name not in period_name:

                if (data[2] in period_year or data[3] in period_descr):
                    continue
                elif not validate_period(data[2]):
                    continue
                else:

                    new_model = {
                        'name': data[1], 
                        'time_of_period': data[2], 
                        'descr': data[3]
                    }

                    p = Period(**new_model)
                    p.save()
            else:
                for period in period_values:
                    if name != period['name']:
                        continue

                    else:
                        if (data[2] in period_values or data[3] in period_values):
                            continue
                        if validate_period(data[2]):
    
                            time_of_period = data[2]
                            descr = data[3]

                            Period.objects.filter(pk=period['id']).update(
                                time_of_period=time_of_period, descr=descr)

    period_values = Period.objects.order_by(
        'time_of_period').values('time_of_period', 'name', 'id')
    header = list(period_values[0].keys())[:-1]
    content_period = list(period_values)
    period_list = Period.objects.order_by('time_of_period')

                
    return render(request, 'music_search/periods.html', {
        'uploaded_file_url': uploaded_file_url,
        'header': header,
        'content_period': content_period,
        'period_list': period_list
    })


def get_per_file(request):
    periods = Period.objects.all()
    template_name = 'music_search/periods.html'

    output = io.BytesIO()

    workbook = xlsxwriter.Workbook(output)
    worksheet_s = workbook.add_worksheet("Summary")
    title = workbook.add_format({
        'bold': True,
        'font_size': 14,
        'align': 'center',
        'valign': 'vcenter'
    })
    header = workbook.add_format({
        'bg_color': '#F7F7F7',
        'color': 'black',
        'align': 'center',
        'valign': 'top',
        'border': 1
    })
    cell = workbook.add_format({
        'align': 'left',
        'valign': 'top',
        'text_wrap': True,
        'border': 1
    })
    cell_center = workbook.add_format({
        'align': 'center',
        'valign': 'top',
        'border': 1
    })

    worksheet_s.write(0, 0, ugettext("No"), header)
    worksheet_s.write(0, 1, ugettext("name"), header)
    worksheet_s.write(0, 2, ugettext("time"), header)
    worksheet_s.write(0, 3, ugettext("descr"), header)

    description_col_width = 10

    for idx, data in enumerate(periods):
        row = 1 + idx
        worksheet_s.write_number(row, 0, idx + 1, cell_center)
        worksheet_s.write_string(row, 1, data.name, cell)
        worksheet_s.write_string(row, 2, data.time_of_period, cell_center)
        worksheet_s.write_string(row, 3, data.descr, cell)
        if len(data.descr) > description_col_width:
            description_col_width = len(data.descr)

    workbook.close()
    output.seek(0)
    response = HttpResponse(
        output,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
    return response


class CompousersView(LoginRequiredMixin, generic.ListView):
    model = Compouser
    template_name = 'music_search/compousers.html'
    login_url = '/login/'
=======
class CompousersView(generic.ListView):
    model = Compousers
    template_name = 'music_search/compousers.html'
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e

    def chart(self):
        dataSource = {}
        dataSource['chart'] = {
            "caption": "Compousers in Periods chart",
            "numberPrefix": "$",
            "bgColor": "#ffffff",
            "startingAngle": "310",
            "centerLabelBold": "1",
            "showTooltip": "0",
            "decimals": "0",
            "theme": "fusion"
        }
<<<<<<< HEAD

        dataSource['data'] = []

        for key in Period.objects.annotate(num_compousers=Count('compouser')):
            data = {}
            data['label'] = key.name
            data['value'] = key.num_compousers
=======
        dataSource['data'] = []

        Renesans_comp = 0
        Baroque_comp = 0
        Classical_comp = 0
        Romatic_comp = 0
        Postmod = 0

        for key in Compousers.objects.all():
            if key.period.name == 'Baroque':
                Baroque_comp += 1
            elif key.period.name == 'Renaissance':
                Renesans_comp += 1
            elif key.period.name == 'Classical':
                Classical_comp += 1
            elif key.period.name == 'Romantic':
                Romatic_comp += 1

        periods = [Classical_comp, Baroque_comp,
                   Romatic_comp, Renesans_comp, Postmod]

        index = 0
        for key in Period.objects.all():
            data = {}
            data['label'] = key.name
            data['value'] = periods[index]
            index += 1
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
            dataSource['data'].append(data)

        pie2D = FusionCharts(type="doughnut2d", id="ex1", width="550", height="450",
                             renderAt="chart-container", dataFormat="json", dataSource=dataSource)

        return pie2D
<<<<<<< HEAD
=======

    def get_context_data(self, **kwargs):
        context = super(CompousersView, self).get_context_data(**kwargs)
        compouser_values = Compousers.objects.order_by(
            'birth_date').values('name', 'birth_date', 'death_date', 'id')
        index = 0
        for comp in compouser_values:
            c = Compousers.objects.get(pk=comp['id'])
            compouser_values[index]['period'] = c.period.name
            del compouser_values[index]['id']
            compouser_values[index]['id'] = c.id
            index += 1
        context['compousers_list'] = Compousers.objects.order_by('birth_date')
        context['header'] = list(compouser_values[0].keys())[:-1]
        context['content_compousers'] = list(compouser_values)

music_search/templates/music_search/compousers.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Mr+Dafoe&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
<<<<<<< HEAD
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
    {% block title %}<title>{{section}}</title>{% endblock %}
    <link rel="stylesheet" href="{% static "music_search/css/style.css" %}" type="text/css">
</head>
<body>
    <section>
        {% block table-header %}
            <h1 class="table-name">Compousers data list</h1>
        {% endblock %}
        {% block create_button %}
            <a href="{% url 'music_search:create_compouser' %}" class="button" >Create Compouser</a>
        {% endblock %}
<<<<<<< HEAD
        {% block excel_button %}
            <form action="" method = "GET"> 
                {% csrf_token %}
                <a href="{% url 'music_search:excel_compouser' %}" class="button" download>Get Excel</a>
            </form>
        {% endblock %}
        {% block up_excel_button %}
        <div class="upload-excel-button-wrapper">
            <form action={% url 'music_search:post_excel_compouser' %} method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="button-upload">Upload</button>
                <input type="file" name="excel-file" id="excel-file" class="inputfile">
                <label for="excel-file">Choose a file</label>
            </form>
        </div>
        {% endblock %}
        {% if uploaded_file_url %}
            <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
        {% endif %}
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
        {% if compousers_list %}
        {% block table %}
        <table class="db-table">
            {% block header %}
            <thead>
                <tr>
                {% for key in header %}
<<<<<<< HEAD
                    {% if key == "birth_date" %}
                        <th>
                            {{'birth date'}}
                        </th>
                    {% elif key == "death_date" %}
                        <th>
                            {{'death date'}}
                        </th>
                    {% else %}
                        <th>
                            {{key}}
                        </th>
                    {% endif %}
=======
                    <th>
                        {{key}}
                    </th>
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
                {% endfor %}
                    <th>
                        action
                    </th>
                </tr>
            </thead>
            {% endblock %}

            {% block content %}
            <tbody>
                {% for compouser in content_compousers %}
                    <tr>
                        {% for k, v in compouser.items %}
                            {% if not forloop.last %}
                            <td>
                                {{v}}
                            </td> 
                            {% else %}
                            {% endif %}
                        {% endfor %}
                        <td class ="db-table__action">
                            <ul class = "db-table__action-list">
                                <li>
                                    <a href="{% url 'music_search:detail_compouser' compouser.id  %}">
                                        Detail
                                    </a>
                                </li>   
                                <li>
                                    <a href="{% url 'music_search:edit_compouser' compouser.id %}">
                                        Edit
                                    </a>
                                </li>
                                <li>
<<<<<<< HEAD
                                    <a href="{% url 'music_search:delete_compouser' compouser.id %}">
                                        Delete
                                    </a> 
                                </li> 
                            </ul> 
                        </td> 
                    </tr> 
                {% endfor %} 
            </tbody> 
            {% endblock %} 
        </table> 
        <div id="chart-container">{{ chart_compousers|safe }}</div> 
        {% endblock %} 
        {% else %} 
            <p>No compousers are available.</p>
        {% endif %} 
    </section> 
</body> 
</html> 
=======
                                    <a>
                                        Delete
                                    </a>
                                    
                                </li>
                            </ul> 
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            {% endblock %}    
        </table>
        <div id="chart-container">{{ chart_compousers|safe }}</div>
        {% endblock %}
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </section>
</body>
</html>
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e

music_search/templates/music_search/compousers_delete.html
{% extends "base_delete.html" %}
{% load widget_tweaks %}

{% block form_delete %}
    {{object}}
{% endblock %}

music_search/templates/music_search/compousers_detail.html
{% extends "base_detail.html" %}

{% block title %} {{object.name}} {% endblock %} 
<<<<<<< HEAD
{% block detail %}
    {{object.name}}
{% endblock %}
=======
{% block detail %}{{object.name}}  {% endblock %}
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e

music_search/templates/music_search/compousers_edit.html
{% extends "base_edit.html" %}

{% block form_edit %}
<<<<<<< HEAD
    {{ form.name }}
=======

{{ form.name }}

>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
{% endblock %}

music_search/templates/music_search/music.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Mr+Dafoe&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "music_search/css/style.css" %}" type="text/css">
    {% block title %}<title>{{section}}</title>{% endblock %}
</head>
<body>
    <section>
        {% block table-header %}
            <h1 class="table-name">Music data list</h1>
        {% endblock %}

        {% block create_button %}
            <a href="{% url 'music_search:create_music' %}" class="button" >Create Music</a>
        {% endblock %}

        {% block excel_button %}
            <form action="" method = "GET"> 
                {% csrf_token %}
                <a href="{% url 'music_search:excel_music' %}" class="button" download>Get Excel</a>
            </form>
        {% endblock %}

        {% block up_excel_button %}
        <div class="upload-excel-button-wrapper">
            <form action={% url 'music_search:post_excel_music' %} method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="button-upload">Upload</button>
                <input type="file" name="excel-file" id="excel-file" class="inputfile">
                <label for="excel-file">Choose a file</label>
            </form>
        </div>
        {% endblock %}

        {% if uploaded_file_url %}
            <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
        {% endif %}

        {% if music_list %}
        {% block table %}
        <table class="db-table">
            {% block header %}
            <thead>
                <tr>
                {% for key in header %}
                    {% if key == 'year_written' %}
                        <th>
                            {{'year written'}}
                        </th>
                    {% elif key == 'type_of_piece' %}
                        <th>
                            {{'type'}}
                        </th>
                    {% else %}
                        <th>
                            {{key}}
                        </th>
                    {% endif %}
                {% endfor %}
                    <th>
                        action
                    </th>
                </tr>
            </thead>
            {% endblock %}

            {% block content %}
            <tbody>
                {% for music in content_music %}
                    <tr>
                        {% for k, v in music.items %}
                            {% if not forloop.last %}
                            <td>
                                {{v}}
                            </td> 
                            {% else %}
                            {% endif %}
                        {% endfor %}
                        <td class ="db-table__action">
                            <ul class = "db-table__action-list">
                                <li>
                                    <a href="{% url 'music_search:detail_music' music.id %}">
                                        Detail
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'music_search:edit_music' music.id %}">
                                        Edit
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'music_search:delete_music' music.id %}">
                                        Delete
                                    </a>
                                </li>

                            </ul> 
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            {% endblock %}    
        </table>
        <div id="chart-container">{{ chart_music|safe }}</div>
        {% endblock %}
        {% else %}
            <p>No music are available.</p>
        {% endif %}
    </section>
</body>
</html>

music_search/templates/music_search/music_delete.html
{% extends "base_delete.html" %}
{% load widget_tweaks %}

{% block form_delete %}
    {{object}}
{% endblock %}

music_search/templates/music_search/periods.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Mr+Dafoe&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
<<<<<<< HEAD
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
=======
    {% block title %}<title>{{section}}</title>{% endblock %}
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
    <link rel="stylesheet" href="{% static "music_search/css/style.css" %}" type="text/css">
    {% block title %}<title>{{section}}</title>{% endblock %}
</head>
<body>
    <section>
        {% block table-header %}<h1 class="table-name">Period data list</h1>{% endblock %}
        {% block create_button %}
                    <a href="{% url 'music_search:create_period' %}" class="button" >Create Period</a>
        {% endblock %}
<<<<<<< HEAD
        {% block excel_button %}
            <form action="" method = "GET"> 
                {% csrf_token %}
                <a href="{% url 'music_search:excel_period' %}" class="button" download>Get Excel</a>
            </form>
        {% endblock %}
        {% block up_excel_button %}
        <div class="upload-excel-button-wrapper">
            <form action={% url 'music_search:post_excel_period' %} method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="button-upload">Upload</button>
                <input type="file" name="excel-file" id="excel-file" class="inputfile">
                <label for="excel-file">Choose a file</label>
            </form>
        </div>
        {% endblock %}
        {% if uploaded_file_url %}
            <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
        {% endif %}
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
        {% if period_list %}
        {% block table %}
        <table class="db-table">
            {% block header %}
            <thead>
                <tr>
                {% for key in header %}
                    {% if key == 'time_of_period' %}
                        <th>
                            {{'time of period'}}
                        </th>
                    {% else %}
                        <th>
                            {{key}}
                        </th>
                    {% endif %}
                {% endfor %}
                    <th>
                        action
                    </th>
                </tr>
            </thead>
            {% endblock %}

            {% block content %}
            <tbody>
                {% for period in content_period %}
                    <tr>
                        {% for k, v in period.items %}
                            {% if not forloop.last %}
                            <td>
                                {{v}}
                            </td> 
                            {% else %}
                            {% endif %}
                        {% endfor %}
                        <td class ="db-table__action">
                            <ul class = "db-table__action-list">
                                <li>
                                    <a href="{% url 'music_search:detail_period' period.id  %}">
                                        Detail
                                    </a>
                                </li>   
                                <li>
                                    <a href="{% url 'music_search:edit_period' period.id %}">
                                        Edit
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'music_search:delete_period' period.id %}">
                                        Delete
                                    </a>
                                </li>
                            </ul> 
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            {% endblock %}    
        </table>
        {% endblock %}
        {% else %}
            <p>No periods are available.</p>
        {% endif %}
    </section>
</body>
</html>