DolceMusic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('search/', include('music_search.urls')),
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path('log/', include('accounts.urls')),
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
    path('', views.home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from . import views
app_name = 'accounts'
urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
]

music_search/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'music_search'
urlpatterns = [
    path('', views.index, name='index'),
    # periods path
    path('periods/', views.PeriodView.as_view(), name='period'),
    path('periods/downl', views.get_per_file, name='excel_period'),
    path('periods/excel_upd', views.post_per_file, name='post_excel_period'),
    path('periods/<int:pk>/details',
         views.DetailView.as_view(), name='detail_period'),
    path('periods/<int:pk>/edit',
         views.PeriodUpdate.as_view(), name='edit_period'),
    path('periods/create', views.PeriodCreate.as_view(), name='create_period'),
<<<<<<< HEAD
    path('periods/<int:pk>/delete',
         views.PeriodDelete.as_view(), name='delete_period'),
    # compousers path
    path('compousers/downl', views.get_comp_file, name='excel_compouser'),
    path('compousers/excel_upd', views.post_comp_file, name='post_excel_compouser'),
=======
    # compousers path
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
    path('compousers/', views.CompousersView.as_view(), name='compouser'),
    path('compousers/<int:pk>/details',
         views.CompousersDetailView.as_view(), name='detail_compouser'),
    path('compousers/<int:pk>/edit',
         views.CompousersUpdate.as_view(), name='edit_compouser'),
    path('compousers/create_compouser', views.CompousersCreate.as_view(),
<<<<<<< HEAD
         name='create_compouser'),
    path('compousers/<int:pk>/delete',
         views.CompousersDelete.as_view(), name='delete_compouser'),
     # music path
     path('music/downl', views.get_music_file, name='excel_music' ),
     path('music/excel_upd', views.post_music_file, name='post_excel_music'),
     path('music/', views.PieceOfMusicView.as_view(), name='music'),
     path('music/<int:pk>/details', views.MusicDetailView.as_view(), name='detail_music'),
     path('music/<int:pk>/edit', views.PieceOfMusicUpdate.as_view(), name='edit_music'),
     path('music/create_music', views.PieceOfMusicCreate.as_view(), name='create_music'),
     path('music/<int:pk>/delete', views.PieceOfMusicDelete.as_view(), name='delete_music')
=======
         name='create_compouser')
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_search/forms.py
from django import forms
from django.core.validators import RegexValidator
<<<<<<< HEAD
from django.contrib.auth.forms import ReadOnlyPasswordHashField
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
from django.forms import ModelForm
from .validators import *
from .models import *

<<<<<<< HEAD
=======

>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
class PeriodForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', }), validators=[RegexValidator(regex='^\w+$')])
    time_of_period = forms.CharField(validators=[RegexValidator(
        regex='^[1-9]([0-9]{3})[-][1-9]([0-9]{3})$', message='invalid time period', code='invalid_period'), validate_year], widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Period
        fields = '__all__'

    def clean(self):
        cleaned_data = super(PeriodForm, self).clean()
        time_of_period = cleaned_data.get("time_of_Period")
        name = cleaned_data.get("name")
        descr = cleaned_data.get("descr")
        if name is not None and time_of_period is not None and descr is not None:
            if not validate_year(time_of_period):
                raise ValidationError('incorect period year validation')
            elif name == None:
                raise ValidationError('name cannot be empty')


class CompousersForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', }), validators=[RegexValidator(regex='\w+')])
    birth_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control'}))
    death_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control'}))

    class Meta:
<<<<<<< HEAD
        model = Compouser
=======
        model = Compousers
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
        fields = '__all__'

    def clean(self):
        cleaned_data = super(CompousersForm, self).clean()
        name = cleaned_data.get("name")
        birth_date = cleaned_data.get("birth_date")
        death_date = cleaned_data.get("death_date")

<<<<<<< HEAD
class MusicForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', }), validators=[RegexValidator(regex='\w+')])
    year_written = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control'}))
    class Meta:
        model = PieceOfMusic
        fields = '__all__'

    def clean(self):
        cleaned_data = super(MusicForm, self).clean()
        name = cleaned_data.get("name")
        year_written = cleaned_data.get("year_written")

=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e

'''class PeriodEditFrom(forms.Form):
    period_name = forms.CharField(lable='Period name', max_length = 100)
    period_time = forms.CharField(lable='Period time', max_length = 9)'''

music_search/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.template.response import TemplateResponse
from django.http import HttpResponse, request, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
<<<<<<< HEAD
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.template.defaulttags import register

import openpyxl
import io
import xlsxwriter
from django.utils.translation import ugettext
from .fusioncharts import FusionCharts
import re

from .forms import *
from .models import *
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .decorators import admin_required
=======
from .forms import *
from .models import *
from .fusioncharts import FusionCharts
#from .forms import PeriodEditFrom
# Create your views here.
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e


@login_required
def index(request):
    return TemplateResponse(request, 'search.html', {})


def home_view(request):
    period_values = Period.objects.order_by('time_of_period').values('name')
    context = {'period_names': period_values}

    return render(request, 'music_search/index.html', context)

def validate_period(value):
    characters = value.split('-')
    check = True

    if len(characters) != 2:
        return False

    first_date = characters[0]
    second_date = characters[1]

    if not first_date.isdigit() or not second_date.isdigit():
        return False
    else:
        first_date = int(first_date)
        second_date = int(second_date)

    if first_date >= second_date:
        check = False

    if second_date - first_date > 500:
        check = False

    return check

def validate_date(value):
    check = False
    if re.match(r"([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))", value):
        check = True
    return check

class PeriodView(LoginRequiredMixin, generic.ListView):
    model = Period
    template_name = 'music_search/periods.html'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super(PeriodView, self).get_context_data(**kwargs)

        period_values = Period.objects.order_by(
            'time_of_period').values('time_of_period', 'name', 'id')
        context['period_list'] = Period.objects.order_by('time_of_period')
        context['header'] = list(period_values[0].keys())[:-1]
        context['content_period'] = list(period_values)
        return context

@admin_required
def post_per_file(request):
    periods = Period.objects.all()
    period_values = Period.objects.order_by(
        'time_of_period').values('time_of_period', 'name', 'descr', 'id')
    
    template_name = 'music_search/periods.html'

    if request.method == 'POST' and request.FILES['excel-file']:
        excel_file = request.FILES['excel-file']
        fs = FileSystemStorage()
        filename = fs.save(excel_file.name, excel_file)
        uploaded_file_url = fs.url(filename)

<<<<<<< HEAD
        wb = openpyxl.load_workbook(excel_file)

        worksheet = wb[wb.sheetnames[0]]

        period_name = [period['name'] for period in period_values]
        period_year = [period['time_of_period'] for period in period_values]
        period_descr = [period['descr'] for period in period_values]

        
        i = 0
        for data in worksheet.iter_rows(min_row=1, max_col=4, values_only=True):
    
            if i == 0:
                i += 1
                continue
            i += 1

            name = data[1]

            if name == None:
                break

            elif name not in period_name:

                if (data[2] in period_year or data[3] in period_descr):
                    continue
                elif not validate_period(data[2]):
                    continue
                else:

                    new_model = {
                        'name': data[1], 
                        'time_of_period': data[2], 
                        'descr': data[3]
                    }

                    p = Period(**new_model)
                    p.save()
            else:
                for period in period_values:
                    if name != period['name']:
                        continue

                    else:
                        if (data[2] in period_values or data[3] in period_values):
                            continue
                        if validate_period(data[2]):
    
                            time_of_period = data[2]
                            descr = data[3]

                            Period.objects.filter(pk=period['id']).update(
                                time_of_period=time_of_period, descr=descr)

    period_values = Period.objects.order_by(
        'time_of_period').values('time_of_period', 'name', 'id')
    header = list(period_values[0].keys())[:-1]
    content_period = list(period_values)
    period_list = Period.objects.order_by('time_of_period')

                
    return render(request, 'music_search/periods.html', {
        'uploaded_file_url': uploaded_file_url,
        'header': header,
        'content_period': content_period,
        'period_list': period_list
    })


def get_per_file(request):
    periods = Period.objects.all()
    template_name = 'music_search/periods.html'

    output = io.BytesIO()

    workbook = xlsxwriter.Workbook(output)
    worksheet_s = workbook.add_worksheet("Summary")
    title = workbook.add_format({
        'bold': True,
        'font_size': 14,
        'align': 'center',
        'valign': 'vcenter'
    })
    header = workbook.add_format({
        'bg_color': '#F7F7F7',
        'color': 'black',
        'align': 'center',
        'valign': 'top',
        'border': 1
    })
    cell = workbook.add_format({
        'align': 'left',
        'valign': 'top',
        'text_wrap': True,
        'border': 1
    })
    cell_center = workbook.add_format({
        'align': 'center',
        'valign': 'top',
        'border': 1
    })

    worksheet_s.write(0, 0, ugettext("No"), header)
    worksheet_s.write(0, 1, ugettext("name"), header)
    worksheet_s.write(0, 2, ugettext("time"), header)
    worksheet_s.write(0, 3, ugettext("descr"), header)

    description_col_width = 10

    for idx, data in enumerate(periods):
        row = 1 + idx
        worksheet_s.write_number(row, 0, idx + 1, cell_center)
        worksheet_s.write_string(row, 1, data.name, cell)
        worksheet_s.write_string(row, 2, data.time_of_period, cell_center)
        worksheet_s.write_string(row, 3, data.descr, cell)
        if len(data.descr) > description_col_width:
            description_col_width = len(data.descr)

    workbook.close()
    output.seek(0)
    response = HttpResponse(
        output,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
    return response


class CompousersView(LoginRequiredMixin, generic.ListView):
    model = Compouser
    template_name = 'music_search/compousers.html'
    login_url = '/login/'
=======
class CompousersView(generic.ListView):
    model = Compousers
    template_name = 'music_search/compousers.html'
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e

    def chart(self):
        dataSource = {}
        dataSource['chart'] = {
            "caption": "Compousers in Periods chart",
            "numberPrefix": "$",
            "bgColor": "#ffffff",
            "startingAngle": "310",
            "centerLabelBold": "1",
            "showTooltip": "0",
            "decimals": "0",
            "theme": "fusion"
        }
<<<<<<< HEAD

        dataSource['data'] = []

        for key in Period.objects.annotate(num_compousers=Count('compouser')):
            data = {}
            data['label'] = key.name
            data['value'] = key.num_compousers
=======
        dataSource['data'] = []

        Renesans_comp = 0
        Baroque_comp = 0
        Classical_comp = 0
        Romatic_comp = 0
        Postmod = 0

        for key in Compousers.objects.all():
            if key.period.name == 'Baroque':
                Baroque_comp += 1
            elif key.period.name == 'Renaissance':
                Renesans_comp += 1
            elif key.period.name == 'Classical':
                Classical_comp += 1
            elif key.period.name == 'Romantic':
                Romatic_comp += 1

        periods = [Classical_comp, Baroque_comp,
                   Romatic_comp, Renesans_comp, Postmod]

        index = 0
        for key in Period.objects.all():
            data = {}
            data['label'] = key.name
            data['value'] = periods[index]
            index += 1
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
            dataSource['data'].append(data)

        pie2D = FusionCharts(type="doughnut2d", id="ex1", width="550", height="450",
                             renderAt="chart-container", dataFormat="json", dataSource=dataSource)

        return pie2D
<<<<<<< HEAD
=======

    def get_context_data(self, **kwargs):
        context = super(CompousersView, self).get_context_data(**kwargs)
        compouser_values = Compousers.objects.order_by(
            'birth_date').values('name', 'birth_date', 'death_date', 'id')
        index = 0
        for comp in compouser_values:
            c = Compousers.objects.get(pk=comp['id'])
            compouser_values[index]['period'] = c.period.name
            del compouser_values[index]['id']
            compouser_values[index]['id'] = c.id
            index += 1
        context['compousers_list'] = Compousers.objects.order_by('birth_date')
        context['header'] = list(compouser_values[0].keys())[:-1]
        context['content_compousers'] = list(compouser_values)

music_search/templates/base.html
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:register' as register_url %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
	<script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Mr+Dafoe&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "music_search/css/style.css" %}"  type="text/css">
    {% block title %}<title>Sections Title</title>{% endblock %}
    
</head>
<body>
    <div class="section-wrapper"></div>
    {% block menu %}
    <header>
        <div class="header">
            <nav class="header-nav">
                <ul class="header-nav__items">
                    <li class="header-nav__item">
                        <a class="home" href="/">Dolce Music</a> 
                    </li>
                    <li class="header-nav__item">
                        <a href="{% url 'music_search:period' %}">Periods</a>
                    </li>
                    <li class="header-nav__item">
                        <a href="{% url 'music_search:compouser' %}">Compousers</a>
<<<<<<< HEAD
                    </li>
                    <li class="header-nav__item">
                        <a href="{% url 'music_search:music' %}">Music</a>
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
                    </li>
                </ul>
            </nav>
            <nav class="header-nav">
                <ul class="header-log__items">
                {% if request.user.is_authenticated %}
                    <li class="header-log__item {% if request.path == logout_url %}active{% endif %}">
                        <a class="nav-link" href="{{ logout_url }}">Logout</a>
                    </li>
                {% else %}
                    <li class="header-nav__item {% if request.path == register_url %}active{% endif %}">
                        <a class="nav-link" href="{{ register_url }}">Register</a>
                    </li>
                    <li class="header-nav__item {% if request.path == login_url %}active{% endif %}">
                        <a class="nav-link" href="{{ login_url }}">Login</a>
                    </li>
                {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    {% endblock %}
        <section>
                {% block table-header %}<h1 class="table-name">Topic</h1>{% endblock %}
<<<<<<< HEAD
                <ul class = "features-buttons">
                    <li class="features-button">
                        {% block create_button %}
                            <a href="base_create.html" class="button" >Create </a>
                        {% endblock %}
                    </li>
                    <li class="features-button">
                        {% block excel_button %}
                            <form action="">
                                <input type="button" name="excel" value="Get excel table" />
                            </form>
                        {% endblock %}
                    </li>
                    <li>
                        {% block up_excel_button %}
                        {% endblock %}
                    </li>
                </ul>
=======
                {% block create_button %}
                    <a href="base_create.html" class="button" >Create </a>
                {% endblock %}
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
                {% block table %}
                <table class="db-table">

                    {% block header %}
                    <thead>
                            <tr>
                                <th>
                                    header
                                </th>
                            </tr>
                            
                    </thead>
                    {% endblock %}
                    {% block content %}
                    <tbody>
                        <tr>
                            <td>
                                content
                            </td>
                            <td>
                                <ul>
                                    <li>
                                        <a href="{% url '/' %}">
                                            Detail
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url '/' %}">
                                            Edit
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            Delete
                                        </a>
                                    </li>
                                </ul> 
                            </td>
                        </tr>
                    </tbody>
                    {% endblock %}
                    
                </table> 
                {% endblock %}
        </section>
    <footer class="main-footer">
        <nav>
            <ul class="main-footer__links">
                <li class="main-footer__link">
                    <a href="search.html" >search</a>
                </li>
                <li class="main-footer__link">
                    <a href="index.html" >home
                    </a>
                </li>
            </ul>
        </nav>
    </footer>
</body>
</html>

music_search/templates/base_create.html
{% load static %} 
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Mr+Dafoe&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
<<<<<<< HEAD
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "music_search/css/style.css" %}"  type="text/css">
    <title> {% block title %}Doc{% endblock %}</title>
</head>
<body>
    <header>
        <div class="header">
            <nav class="header-nav">
<<<<<<< HEAD
                <ul class="header-nav__items">
                    <li class="header-nav__item">
                        <a class="home" href="/">Dolce Music</a> 
                    </li>
                    <li class="header-nav__item">
                        <a href="{% url 'music_search:period' %}">Periods</a>
                    </li>
                    <li class="header-nav__item">
                        <a href="{% url 'music_search:compouser' %}">Compousers</a>
                    </li>
                    <li class="header-nav__item">
                        <a href="{% url 'music_search:music' %}">Music</a>
                    </li>
=======
                <ul>
                    <li>
                        <a class="home" href="/">Dolce Music</a> 
                    </li>
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
                </ul>
            </nav>
        </div>
    </header>
    <main>
        <section>
            <div>
                <h1>Create Period</h1>
                {% block formcreate %}
                <form method="post" novalidate>
                    {% csrf_token %}
                
                    {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                    {% endfor %}
                
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{ field.label_tag }}
                    
                        {% if form.is_bound %}
                        {% if field.errors %}
                            {% render_field field class="form-control is-invalid" %}
                            {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                        {% else %}
                            {% render_field field class="form-control is-valid" %}
                        {% endif %}
                        {% else %}
                        {% render_field field class="form-control" %}
                        {% endif %}
                
                        {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                    </div>
                    {% endfor %}
                
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                {% endblock %}
            </div>
        </section>
    </main>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

music_search/templates/index.html
<<<<<<< HEAD
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:register' as register_url %}
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<<<<<<< HEAD
    
    <link href="https://fonts.googleapis.com/css?family=Mr+Dafoe&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "music_search/css/home.css" %}" type="text/css">
=======
    <link rel="stylesheet" href="{% static "music_search/css/home.css" %}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Mr+Dafoe&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500&display=swap" rel="stylesheet">
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
    <title>Dolce Music</title>
</head>
<body>
    <main>
        <section class="home-banner">
            <header>
                <div class="header">
                    <nav class="header-nav">
                        <ul>
                            <li>
                                <a class="home" href="/">Dolce Music</a> 
                            </li>
                            <li>
                                <a class="search" href="{% url 'music_search:index' %}">Search</a>
                            </li>
                        </ul>
                    </nav>
<<<<<<< HEAD
                    <nav class="header-nav">
                        <ul class="header-log__items">
                        {% if request.user.is_authenticated %}
                            <li class="header-log__item {% if request.path == logout_url %}active{% endif %}">
                                <a class="nav-link" href="{{ logout_url }}">Logout</a>
                            </li>
                        {% else %}
                            <li class="header-nav__item {% if request.path == register_url %}active{% endif %}">
                                <a class="nav-link" href="{{ register_url }}">Register</a>
                            </li>
                            <li class="header-nav__item {% if request.path == login_url %}active{% endif %}">
                                <a class="nav-link" href="{{ login_url }}">Login</a>
                            </li>
                        {% endif %}
                        </ul>
                    </nav>
=======
>>>>>>> 3c85a009d41e0aa88e8966791cf5bf3e6148b68e
                </div>
            </header>
            <div class="banner-info">
                <h1>Just music. Just for you</h1>
                <div class="banner">
                    <h2>Magazine</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse in magna vel felis cursus fringilla at eu nisl. Aliquam erat volutpat. Nulla porta gravida felis eu efficitur. Pellentesque dapibus lobortis magna, at elementum libero. In fermentum nisi a dui sollicitudin posuere. Vivamus bibendum lacus a mauris vulputate, et maximus justo interdum. Nulla et imperdiet lectus, quis ultricies magna. Donec auctor gravida sodales.
                    </p>
                </div>
            </div>
        </section>
        <section>
            <div class="popular-section">
                <h1>Popular search list</h1>
                
            </div>
        </section>
    </main>
    <footer class="main-footer">
            <nav>
                <ul class="main-footer__links">
                    <li class="main-footer__link">
                        <a href="search.html" >search</a>
                    </li>
                    <li class="main-footer__link">
                        <a href="index.html" >home
                        </a>
                    </li>
                </ul>
            </nav>
    </footer>
</body>
</html>